apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-configmap-vars
  labels:
  {{- include "app.labels" . | nindent 4 }}
data:
  VAR4: {{ .Values.configmapVars.var4 | quote }}